# Generated by Django 5.1.6 on 2026-02-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_studentemail_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.ImageField(upload_to='')),
                ('productDescription', models.CharField(max_length=50)),
                ('productStock', models.PositiveIntegerField()),
                ('productColor', models.CharField(max_length=50, null=True)),
                ('productStatus', models.BooleanField(default=True)),
            ],
        ),
    ]
