# Generated by Django 5.1.6 on 2026-02-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='sportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportitemName', models.CharField(max_length=100)),
                ('sportitemPrice', models.IntegerField()),
                ('sportitemDescription', models.CharField(max_length=100)),
                ('sportitemQuntity', models.IntegerField()),
                ('sportitemColor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.IntegerField(),
        ),
    ]
