# Generated by Django 5.1.6 on 2026-02-06 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_sportitem_alter_product_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentHobbies', models.CharField(choices=[('reading', 'reading'), ('travel', 'travel'), ('music', 'music')], max_length=100)),
                ('studentAddress', models.CharField(max_length=100)),
                ('studentPhone', models.CharField(max_length=100)),
                ('studentGender', models.CharField(max_length=100)),
                ('studentDOB', models.DateField()),
                ('studentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
