# Generated by Django 5.1.6 on 2026-02-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentprofile',
            table='studentProfile',
        ),
    ]
