# Generated by Django 5.1.6 on 2026-02-06 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_category_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userAge', models.IntegerField()),
                ('userEmail', models.EmailField(max_length=254, null=True)),
                ('userPhone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='bankdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=100)),
                ('accountNumber', models.TextField()),
                ('accountType', models.CharField(max_length=100)),
                ('ifscCode', models.TextField()),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
            options={
                'db_table': 'bankdetail',
            },
        ),
    ]
