# Generated by Django 5.1.6 on 2026-02-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_user_bankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=100)),
                ('clientage', models.IntegerField()),
                ('clientCity', models.CharField(max_length=100)),
                ('clientEmail', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='accountName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='accountType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.category'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='sportitem',
            table='sportitem',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=100)),
                ('carCompany', models.CharField(max_length=100)),
                ('carPrice', models.IntegerField()),
                ('carmodel', models.TextField()),
                ('cardeatils', models.CharField(max_length=100)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.client')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
