# Generated by Django 5.1.6 on 2026-02-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_client_alter_bankdetail_accountname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='accountName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='accountType',
            field=models.CharField(max_length=100),
        ),
    ]
