# Generated by Django 5.1.6 on 2026-02-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_bankdetail_accountname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=100)),
                ('personAge', models.IntegerField()),
                ('personEmail', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BikeName', models.CharField(max_length=100)),
                ('BikeikeCompany', models.CharField(max_length=100)),
                ('BikeikePrice', models.IntegerField()),
                ('Bikeikemodel', models.TextField()),
                ('Bikeikedeatils', models.CharField(max_length=100)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.person')),
            ],
            options={
                'db_table': 'Bike',
            },
        ),
    ]
