# Generated by Django 6.0.2 on 2026-02-09 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.user')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
