# Generated by Django 6.0.2 on 2026-02-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_userid_customer_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='servicestaff',
            old_name='userId',
            new_name='user',
        ),
    ]
