# Generated by Django 6.0.2 on 2026-02-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_admin_table_alter_customer_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='vehicle',
            new_name='vehicleId',
        ),
        migrations.RenameField(
            model_name='parkingdetails',
            old_name='vehicle',
            new_name='vehicleId',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='customer',
            new_name='customerId',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='service',
            new_name='serviceId',
        ),
        migrations.RenameField(
            model_name='servicedetail',
            old_name='staff',
            new_name='staffId',
        ),
        migrations.RenameField(
            model_name='servicedetail',
            old_name='vehicle',
            new_name='vehicleId',
        ),
        migrations.RenameField(
            model_name='transportation',
            old_name='vehicle',
            new_name='vehicleId',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='customer',
            new_name='customerId',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicestaff',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.user'),
        ),
        migrations.AddField(
            model_name='servicestaff',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.user'),
        ),
    ]
